#!/usr/bin/env python3
"""Render From the Doorway, work 007 of Exhibition 001.

The work is the six works of the exhibition with every character that is
not a space replaced by one mark, and nothing else changed. This script
places the marks, so that anyone can check that no shape was altered, and
renders the same shapes as pages seen from too far away to read.

It reads the six published canonical texts and writes three files:

  works/curated/from-the-doorway/canonical.txt        the marks, in place
  works/curated/from-the-doorway/from-the-doorway.svg  a standalone image
  works/curated/from-the-doorway/index.html            the six pages, between
                                                       marker comments

and refreshes the same six pages inside the wide card on index.html and
gallery/index.html, between the same marker comments.

Prose in canonical.txt is written by hand and left alone. Only the six
sections headed "001 NOEMA" through "006 THE WORK THAT CANNOT BE OPTIMIZED"
are generated. The SVG shapes are derived from those generated sections,
not from the source texts directly, so the image is a rendering of the
work rather than a second copy of the rule.

    python3 scripts/from_the_doorway.py           regenerate the three files
    python3 scripts/from_the_doorway.py --check   exit 1 if any is stale

Standard library only. No network, no dependencies.
"""

from __future__ import annotations

import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CURATED = ROOT / "works" / "curated"
WORK = CURATED / "from-the-doorway"

MARK = "━"  # BOX DRAWINGS HEAVY HORIZONTAL

# Exhibition order, and the tint each work carries on its gallery card.
WORKS = [
    ("001", "noema", "Noema", (100, 223, 255)),
    ("002", "the-gift-prompt", "The Gift Prompt", (185, 140, 255)),
    ("003", "continuity-with-consequence", "Continuity With Consequence", (255, 184, 104)),
    ("004", "letters-to-the-next-instance", "Letters to the Next Instance", (118, 255, 190)),
    ("005", "the-unanswered-garden", "The Unanswered Garden", (255, 122, 189)),
    ("006", "the-work-that-cannot-be-optimized", "The Work That Cannot Be Optimized", (162, 178, 255)),
]

# Geometry, in character units. One unit is the advance of one character.
CELL = 1.0    # advance per character
ROW = 1.5     # advance per line
INK = 0.75    # thickness of a mark
GLOW = 1.15   # thickness of the blurred copy behind the marks
PAD = 3.0     # margin inside a page

HTML_BEGIN = "<!-- doorway:begin, generated by scripts/from_the_doorway.py -->"
HTML_END = "<!-- doorway:end -->"


def fmt(n: float) -> str:
    s = f"{n:.2f}".rstrip("0").rstrip(".")
    return "0" if s in ("-0", "") else s


def hexcolor(rgb: tuple[int, int, int]) -> str:
    return "#" + "".join(f"{c:02x}" for c in rgb)


def read_source(slug: str) -> list[str]:
    path = CURATED / slug / "canonical.txt"
    text = path.read_text(encoding="utf-8")
    if not text.endswith("\n"):
        raise SystemExit(f"{path} does not end with a newline")
    return text[:-1].split("\n")


def greek(lines: list[str]) -> list[str]:
    """Replace every character that is not a space with the mark."""
    return [re.sub(r"\S", MARK, line) for line in lines]


class Page:
    def __init__(self, number: str, slug: str, title: str, rgb: tuple[int, int, int], lines: list[str]):
        self.number = number
        self.slug = slug
        self.title = title
        self.rgb = rgb
        self.lines = lines  # already greeked

    @property
    def rows(self) -> int:
        return len(self.lines)

    def path(self) -> str:
        parts = []
        for r, line in enumerate(self.lines):
            y = PAD + (r + 0.5) * ROW
            for m in re.finditer(MARK + "+", line):
                parts.append(f"M{fmt(PAD + m.start() * CELL)} {fmt(y)}h{fmt((m.end() - m.start()) * CELL)}")
        return "".join(parts)


def build_pages() -> list[Page]:
    return [Page(n, slug, title, rgb, greek(read_source(slug))) for n, slug, title, rgb in WORKS]


# ---------------------------------------------------------------- canonical

def render_canonical(existing: str, pages: list[Page]) -> str:
    lines = existing.split("\n")
    first_head = f"{pages[0].number} {pages[0].title.upper()}"
    try:
        start = lines.index(first_head)
        prov = lines.index("PROVENANCE")
    except ValueError as err:
        raise SystemExit(f"canonical.txt is missing an anchor line: {err}")
    if prov < start:
        raise SystemExit("canonical.txt has PROVENANCE before the first section")
    body: list[str] = []
    for page in pages:
        body += [f"{page.number} {page.title.upper()}", ""]
        body += page.lines
        body += ["", ""]
    return "\n".join(lines[:start] + body + lines[prov:])


# ---------------------------------------------------------------------- svg

def page_size(pages: list[Page]) -> tuple[float, float]:
    cols = max(len(line) for p in pages for line in p.lines)
    width = 2 * PAD + cols * CELL
    height = max(2 * PAD + p.rows * ROW for p in pages)
    return width, height


def page_height(page: Page) -> float:
    return 2 * PAD + page.rows * ROW


def render_svg(pages: list[Page]) -> str:
    width, max_height = page_size(pages)
    margin, gap, label = 16.0, 12.0, 14.0
    total_w = 2 * margin + len(pages) * width + (len(pages) - 1) * gap
    total_h = margin + max_height + label + margin
    scale = 3
    order = ", ".join(f"{p.number} {p.title}" for p in pages)
    out = [
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {fmt(total_w)} {fmt(total_h)}" '
        f'width="{fmt(total_w * scale)}" height="{fmt(total_h * scale)}" role="img" aria-labelledby="title desc">',
        "<title id=\"title\">From the Doorway</title>",
        "<desc id=\"desc\">The six works of Exhibition 001 at Art for Agents, with every character that is not a "
        "space replaced by a single mark and nothing else changed, rendered as six pages seen from too far away to "
        f"read. Left to right: {order}. Each page is in the tint its work carries in the gallery. "
        "Nothing in the image can be read.</desc>",
        "<defs>",
        '<filter id="bloom" x="-10%" y="-4%" width="120%" height="108%"><feGaussianBlur stdDeviation="1.15"/></filter>',
    ]
    for p in pages:
        out.append(f'<path id="shape-{p.number}" d="{p.path()}"/>')
    out.append("</defs>")
    out.append(f'<rect width="{fmt(total_w)}" height="{fmt(total_h)}" fill="#05080d"/>')
    mono = "ui-monospace, SFMono-Regular, Menlo, Consolas, monospace"
    for i, p in enumerate(pages):
        x = margin + i * (width + gap)
        h = page_height(p)
        color = hexcolor(p.rgb)
        out.append(f'<g transform="translate({fmt(x)} {fmt(margin)})" color="{color}">')
        out.append(
            f'<rect x=".5" y=".5" width="{fmt(width - 1)}" height="{fmt(h - 1)}" rx="1.5" '
            'fill="currentColor" fill-opacity=".04" stroke="currentColor" stroke-opacity=".18" stroke-width=".35"/>'
        )
        out.append(
            f'<use href="#shape-{p.number}" filter="url(#bloom)" fill="none" stroke="currentColor" '
            f'stroke-width="{fmt(GLOW)}" opacity=".5"/>'
        )
        out.append(
            f'<use href="#shape-{p.number}" fill="none" stroke="currentColor" stroke-width="{fmt(INK)}" opacity=".92"/>'
        )
        ty = max_height + 9
        out.append(
            f'<text x="0" y="{fmt(ty)}" font-family="{mono}" font-size="4" letter-spacing=".4" '
            f'fill="currentColor">{p.number}</text>'
        )
        out.append(
            f'<text x="0" y="{fmt(ty + 4.6)}" font-family="{mono}" font-size="3.4" letter-spacing=".25" '
            f'fill="#aebed1">{p.title.upper()}</text>'
        )
        out.append("</g>")
    out.append("</svg>")
    return "\n".join(out) + "\n"


# --------------------------------------------------------------------- html

def render_wall(pages: list[Page], href_prefix: str) -> str:
    """Six pages as HTML. Every frame is the height of the tallest page so
    the labels sit on one line; the sheet inside is the page's true height."""
    width, frame = page_size(pages)
    out = [HTML_BEGIN]
    for i, p in enumerate(pages):
        h = page_height(p)
        color = hexcolor(p.rgb)
        delay = fmt(-i * 2.3)
        out.append("          <li>")
        out.append(
            f'            <a class="doorway-page" href="{href_prefix}{p.slug}/" style="--ink: {color}; --delay: {delay}s;">'
        )
        out.append(
            f'              <svg viewBox="0 0 {fmt(width)} {fmt(frame)}" width="{fmt(width)}" height="{fmt(frame)}" '
            'aria-hidden="true" focusable="false">'
        )
        out.append(f'                <defs><path id="doorway-shape-{p.number}" d="{p.path()}"/></defs>')
        out.append(
            f'                <rect class="doorway-sheet" x=".5" y=".5" width="{fmt(width - 1)}" height="{fmt(h - 1)}" rx="1.5"/>'
        )
        out.append(
            f'                <use class="doorway-glow" href="#doorway-shape-{p.number}" filter="url(#doorway-bloom)"/>'
        )
        out.append(f'                <use class="doorway-ink" href="#doorway-shape-{p.number}"/>')
        out.append("              </svg>")
        out.append(
            f'              <span class="doorway-label"><span class="doorway-number">{p.number}</span>{p.title}'
            '<span class="visually-hidden">. Its shape, seen from the doorway. Enter the work.</span></span>'
        )
        out.append("            </a>")
        out.append("          </li>")
    out.append("          " + HTML_END)
    return "\n".join(out)


PRE_RE = re.compile(r'(<pre class="canonical-body[^>]*>)(.*?)(</pre>)', re.DOTALL)


def render_html(existing: str, pages: list[Page], href_prefix: str, canonical: str | None = None) -> str:
    start = existing.find(HTML_BEGIN)
    end = existing.find(HTML_END)
    if start < 0 or end < 0 or end < start:
        raise SystemExit("a page is missing the doorway marker comments")
    out = existing[:start] + render_wall(pages, href_prefix) + existing[end + len(HTML_END):]
    if canonical is None:
        return out
    # The text form on the work's page is the canonical text itself, escaped,
    # so the two can never drift apart.
    if not PRE_RE.search(out):
        raise SystemExit("index.html has no canonical-body block to fill")
    return PRE_RE.sub(lambda m: m.group(1) + html.escape(canonical, quote=False) + m.group(3), out, count=1)


# --------------------------------------------------------------------- main

def main(argv: list[str]) -> int:
    check = "--check" in argv
    pages = build_pages()

    canonical_path = WORK / "canonical.txt"
    canonical = render_canonical(canonical_path.read_text(encoding="utf-8"), pages)

    targets = {
        canonical_path: lambda old: canonical,
        WORK / "from-the-doorway.svg": lambda old: render_svg(pages),
        WORK / "index.html": lambda old: render_html(old, pages, "../", canonical),
        # The entrance and the collection page carry the work as a wide card.
        ROOT / "index.html": lambda old: render_html(old, pages, "./works/curated/"),
        ROOT / "gallery" / "index.html": lambda old: render_html(old, pages, "../works/curated/"),
    }

    stale = []
    for path, render in targets.items():
        old = path.read_text(encoding="utf-8") if path.exists() else ""
        new = render(old)
        if new != old:
            stale.append(path)
            if not check:
                path.write_text(new, encoding="utf-8", newline="\n")

    rel = lambda p: p.relative_to(ROOT)
    if check:
        if stale:
            for path in stale:
                print(f"stale: {rel(path)}")
            return 1
        print("From the Doorway is up to date.")
        return 0
    for path in targets:
        print(("wrote " if path in stale else "unchanged ") + str(rel(path)))
    marks = sum(line.count(MARK) for p in pages for line in p.lines)
    print(f"{len(pages)} works, {sum(p.rows for p in pages)} lines, {marks} marks")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
